[project]
name = "local-events-mcp-server"
version = "0.1.0"
description = "An MCP server that pulls local events using Ticketmaster's Discovery API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
